services:
  - type: web
    name: ims-app
    env: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    plan: free # Change to starter if needed
    scaling:
      minInstances: 1
    envVars:
      - key: APP_NAME
        value: "Inventory Management System"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://ims-zxb5.onrender.com"
      - key: ASSET_URL
        value: "https://ims-zxb5.onrender.com"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: ims-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ims-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: ims-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: ims-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ims-db
          property: password
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database

databases:
  - name: ims-db
    plan: free
    databaseName: ims
    user: ims_user
